### ISSUE TITLE
How to finetune on low resolution images？

### ISSUE THREAD

**Issue by Xie-PC** [zhyever/PatchFusion#12]
Thank you for your good work. 
Now I deal with the depth estimation of 640*360 RGB images, and the ground truth is also of the same size. Your work involves cropped patch of high-resolution images (such as 4K). If I want to finetune my usage scene, I will face particularly small problems after crooping patch. If I first upsample the image to 4K, but I am worried about some inaccurate position values in RGB and depth maps due to interpolation, and artifacts on object boundaries, do you have any treatment methods or suggestions for applying your work to such low-resolution images?

**Comment by zhyever** [comment]
Thanks for your interest in our work. It's indeed hard to directly adopt PatchFusion without any modification on low resolution datasets. One possible way would be proposed in https://github.com/zhyever/PatchFusion/issues/10. I would recommand [Marigold](https://github.com/prs-eth/Marigold) based on your purpose.
