### ISSUE TITLE
conda env

### ISSUE THREAD

**Issue by fangli333** [zhyever/PatchFusion#17]
Hi,

Can I know why if I used conda to set the env, it will a long time to setup?

Thx

**Comment by zhyever** [comment]
Hi, thanks for your interest in our work. I'm also confusing with this issue. Maybe I just install too many things based on ZoeDepth env

**Comment by fangli333** [comment]
I mean if use conda to install the env, how long it approximately take?

**Comment by zhyever** [comment]
:D Sometimes, it stuck forever...
