### ISSUE TITLE
--mode rn working as intended? I don't see a difference

### ISSUE THREAD

**Issue by petermg** [zhyever/PatchFusion#18]
So when I run this with --mode r256, or --mode r1, I get the same results. Is this expected or is something broken? I mean it's WAY FASTER with r1 ;)

--mode r256
![out137_gray](https://github.com/zhyever/PatchFusion/assets/20764493/11ed55aa-86ac-4fbf-9efd-9b5b15043a78)

--mode r1
![out137_gray](https://github.com/zhyever/PatchFusion/assets/20764493/d56528e2-12fc-4729-ae07-dba63403e10b)

**Comment by zhyever** [comment]
There is something different actually. Please note the horizontal stripes on the curtains and plants. With more patches, these artifacts are suppressed, meanwhile the foreground object boundaries are not over-smooth. That's the meaning of the 'local-ensemble' in our paper.
