### ISSUE TITLE
How to run on 6GB vram without out of memory ?

### ISSUE THREAD

**Issue by Michaelwhite34** [zhyever/PatchFusion#19]

**Comment by zhyever** [comment]
The current patch process size is 384x512 default in zoedepth. It would be helpful if you use a smaller size

**Comment by Michaelwhite34** [comment]
> The current patch process size is 384x512 default in zoedepth. It would be helpful if you use a smaller size

Where to edit the size tho?

**Comment by Michaelwhite34** [comment]
> The current patch process size is 384x512 default in zoedepth. It would be helpful if you use a smaller size

Just ran this on Runpod, why is 16bit-raw depth nearly black while the normal depth looks fine ? NVM, it seems I need to multiply by a big number.
