### ISSUE TITLE
How to integrate ZoeD_NK (long distance estimation)

### ISSUE THREAD

**Issue by Mohit-Ak** [zhyever/PatchFusion#20]
First of all, I would like to congratulate on the amazing work. I can totally see the improvements in the output. But I see the config file uses Zoe depth N and the metric depths from it are not accurate for long distances. Can you please tell the changes that we need to make in the config file to accommodate ZoeDepth_NK or ZoeDepth_K?

I tried changing the URL in the bottom of the json but that did not seem to impact the output.

**Comment by zhyever** [comment]
It was kind of difficult based on the previous framework. The new released one can be more flexible. Please refer to the replacement of zoedepth and depth-anything. We'll provide more detailed training docs then.

**Comment by BaderTim** [comment]
Hi @zhyever , I cannot seem to find any more information about what you have said:
> Please refer to the replacement of zoedepth and depth-anything. We'll provide more detailed training docs then.

I would also be interested know if there is an "easy" way to replace zoedepth.
