### ISSUE TITLE
A few problems with user-infer.md

### ISSUE THREAD

**Issue by LastTargaryen** [zhyever/PatchFusion#25]
Orange:
All three of these seem to reference the same directory; to most, though, it looks like three separate directories are being referenced, and so three separate instructions. Extremely confusing and unclear. It appears a language translation is occurring at some point. You must be diligent in asking a person (for whom the language you're unfamiliar with is fluent) to proof-read your GPT translations to ensure accuracy and consistency. These kinds of mistakes will stop a person from being able to run inference...unless that's your goal.

Yellow:
Both of these seem to reference the same directory; to most, though, it looks like three separate directories are being referenced, and so two separate instructions. Extremely confusing and unclear. It appears a language translation is occurring at some point. You must be diligent in asking a person (for whom the language you're unfamiliar with is fluent) to proof-read your GPT translations to ensure accuracy and consistency. These kinds of mistakes will stop a person from being able to run inference...unless that's your goal.

Red:
Some of the arguments seem to be coded so that their associated values or strings are expected before or after certain other arguments
Example: 
bash ./example_shell_script.sh [path to config goes here] [number of GPU cards being used goes here]
This is easy because, if consistency is maintained, a person can easily recall this as

"script>ConfigPath>AmntOfGPUs"

But when you combine the non-hyphenated type with the hyphenated type, it adds many more thought-parameters and so recall is diminished and therefore loses easy reproduction. Is it not possible to just have it so that it only accepts --hyphenated arguments OR just non-hyphenated arguments?? You also reference BOTH types inside of single-quotes--this further confuses, because '--ckpt-path' refers to a hyphenated argument that one must type out, whereas 'gpu_number' seems to refer to an argument whose label needn't be typed out. Even furthermore STILL, 'gpu_number' is shown with an underscore, which (without properly indicating that the argument's corresponding integer or string is expected in a specific order following the name of the script) can lead a user to believe that the inclusion of an underscore must mean that one is
meant to type out the argument.

![Screenshot 2024-03-24 061801](https://github.com/zhyever/PatchFusion/assets/145433667/f6843a7a-177d-4dc5-baa6-6ded4c27fab2)

**Comment by zhyever** [comment]
Thank you for the advice and sorry for any confusion. This user_infer.md was not supposed to be here because it's still under construction. I have deleted it. I will consider these when writing docs

**Comment by zhyever** [comment]
Please check the newest version of docs.
