### ISSUE TITLE
ghost artifacts

### ISSUE THREAD

**Issue by onmygame** [zhyever/PatchFusion#27]
Due to the GPU memory limit, I was only able to test the project on "depthanything_s" and "b" models. However, I noticed the presence of ghost artifacts, especially in the background, in these non-realistic images. I attempted to address this issue by adjusting the HR image resolution, patch split number, and max depth, but unfortunately, the artifacts persist.
Do you have any suggestion?

**Comment by zhyever** [comment]
Hi, would you mind to share some results. It might be bugs, but it would be possible that the model is not strong enough to handle the task. Also, it would be better if you try to use more patchs, like `r128` mode.
