### ISSUE TITLE
question on multiply by 256

### ISSUE THREAD

**Issue by nikky4D** [zhyever/PatchFusion#28]
I have 3 questions:
 -- To convert depth output to PNG, you multiply by 256. Why?
 -- What units are the metric depth output? meters?
 -- What method do you recommend to scale up the depth results to an input image size? 

Thanks

**Comment by zhyever** [comment]
Hi

- I don't know the reason but you could refer to [here](https://huggingface.co/spaces/shariqfarooq/ZoeDepth/blob/main/gradio_depth_pred.py). I just follow the implementation.
- meters, yes.
- As far as I see, if you adopt a reasonably good tiling strategy, the depth result would have the same resolution as the input. It might be not so necessary for an extra upsample. That's the meaning of PatchFusion

Hopefully, the answers are helpful for you
