### ISSUE TITLE
Patchfusion for relative depth to solve sky and ceiling problem

### ISSUE THREAD

**Issue by andrewivan123** [zhyever/PatchFusion#32]
Since metric depth estimation means that the depth of the sky will not be realistic, is it possible to train Patchfusion for relative depth estimation to solve the sky issue?

**Comment by zhyever** [comment]
Hi, some discussions can be found: https://github.com/zhyever/PatchFusion/issues/24

For me, the metric depth estimator provides absolute depth, which is somehow useful in certain practical cases. It would be better to investigate a possible solution for this issue just in a metric setting.

But anyway, it's not difficult to train PatchFusion for relative depth. We just need to change the loss function as far as I can see.
