### ISSUE TITLE
EXR on save

### ISSUE THREAD

**Issue by NickPittas** [zhyever/PatchFusion#4]
Is there an option for EXR save or even png 16bit save for the actual Depth Map? I can see the option when it's gta (1080p) but not u4k (UltraHD)

**Comment by zhyever** [comment]
Ok, I will add the png 16bit save later. As for the exr format, I use it for gta depth loading. I'm not pretty sure about saving depth as exr file actually.

**Comment by zhyever** [comment]
Thanks for your interest in our work.

I have add the support for saving grayscale depth map as well as the 16-bit depth map. Please check out the latest version.

Please use --show/--show_path for grayscale depth map, and use --save/--save_path for the 16-bit png depth map. The overall process is following ZoeDepth.

I'm not familiar with EXR. Welcome to pr if you know how to implement it! Thank you
