### ISSUE TITLE
  config.coarse_branch.pretrained_resource = None AttributeError: 'dict' object has no attribute 'pretrained_resource'

### ISSUE THREAD

**Issue by unite-deals** [zhyever/PatchFusion#41]
Gotten error :\patchfusion.py", line 77, in __init__
    config.coarse_branch.pretrained_resource = None
AttributeError: 'dict' object has no attribute 'pretrained_resource'
Btw I have run in GPU and Latest hugging face package

**Comment by zhyever** [comment]
Hi, a simple way to fix this is to modify line 77 from `config.coarse_branch.pretrained_resource = None` to `config.coarse_branch['pretrained_resource'] = None`. Line 78 should also be changed in the same way.

**Comment by unite-deals** [comment]
Yes, it works.
