### ISSUE TITLE
About trainnig weights and inference

### ISSUE THREAD

**Issue by Hank10032** [zhyever/PatchFusion#5]
Your work is excellent. I would like to inquire about when the trained weights will be released. I tried to infer some images using the method set in GitHub, but it shows that the keys of the model and weights do not match.

**Comment by zhyever** [comment]
Thanks for the interest in our work! I have update the download link. Please check it again. If the weights are still mismatched, please send the error information. Thank you for your help

**Comment by Hank10032** [comment]
Thank you for your patience in answering me.But I still have the following problem when using infer. This is the code I use.
`python ./infer_user.py --model zoedepth_custom --ckp_path /media/TB2/PatchFusion/patchfusion_u4k.pt --model_cfg_path ./zoedepth/models/zoedepth_custom/configs/config_zoedepth_patchfusion.json --rgb_dir /media/TB2/Processed/ADE_20K/image --show --show_path /media/TB2/Processed/ADE_20K/show --save --save_path /media/TB2/Processed/ADE_20K/depth_patch --mode r128 --boundary 0 --blur_mask`
This is the problem
![image](https://github.com/zhyever/PatchFusion/assets/51293383/fc1bba90-0129-4c55-b102-69ddc4a79d29)
Thank you again for your patience

**Comment by zhyever** [comment]
aha, I get it. Please check your timm version. You should have used a higher version timm than 0.6.12. Please downgrade to 0.6.12.

**Comment by Hank10032** [comment]
Thank you for your high-quality and patient answers. All my questions have been solved. Do you have any plans to release batch inference code?
